#!/usr/bin/env bash
### sai-lpc -- command-line Sai liquidity pool client
### Usage: sai-lpc [<options>] <command> [<args>]
###    or: sai-lpc <command> --help
###
### Sai-lpc is a simple two token liquidity pool created for Sai.
### It relies on an external price feed (the `tip`).
###
### Makers
### - `pool` their gems and receive LPS tokens, which are a claim on the pool.
### - `exit` and trade their LPS tokens for a share of the gems in the pool.
###
### Takers
### - `take` and exchange one gem for another, whilst paying a fee
###   (the `gap`). The collected fee goes into the pool.
###
### To conveniently perform ERC20 transfers, see the token(1) program
### available at <https://github.com/dapphub/token>.
###
### Sai-lpc options:
###
###        --lpc=<address>        address of lpc to perform operation on
###
### Transaction options:
###
###    -F, --from=<account>       account from which to send transaction
###    -G, --gas=<number>         amount of gas to provide with transaction

OPTS="sai-lpc [<options>] <command> [<args>]
sai-lpc <command> --help
--
  Options
lpc=address          address of lpc to perform operation on
F,from=address       account from which to send transaction
G,gas=number         amount of gas to provide with transaction
h                    display output in human-readable form
"

set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help -- "$1"
elif [[ $1 = -* ]] && which "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"

while [[ $1 ]]; do
  case $1 in
    --)              shift; break;;

       --lpc)        shift; export SAI_LPC=$1;;

    -F|--from)       shift; export ETH_FROM=$1;;
    -G|--gas)        shift; export ETH_GAS=$1;;

    -h)                     export SAI_HUMAN=1;;

    *) printf "${0##*/}: internal error: %q\n" "$1"; exit 1
  esac; shift
done

export SAI_LPC=${SAI_LPC:-@sai_lpc}

"${0##*/}-${1-help}" "${@:2}"
