#!/usr/bin/env bash
set -ex

test -z $SAI_MOM && exit 1
test -z $SAI_TUB && exit 1
test -z $SAI_TAP && exit 1
test -z $SAI_TOP && exit 1
test -z $SAI_LPC && exit 1

export ETH_GAS=${ETH_GAS:-"100000"}

tub_capabilities="
join(uint128)
exit(uint128)
open()
shut(bytes32)
lock(bytes32,uint128)
free(bytes32,uint128)
draw(bytes32,uint128)
wipe(bytes32,uint128)
give(bytes32,address)
bite(bytes32)
"

tap_capabilities="
boom(uint128)
bust(uint128)
"

top_capabilities="
cash()
"

lpc_capabilities="
pool(address,uint128)
exit(address,uint128)
take(address,uint128)
"

export SETH_ASYNC=yes

for capability in $tub_capabilities; do
    sig=$(seth calldata $capability)
    seth send $SAI_MOM "setRoleCapability(uint8,address,bytes4,bool)" 1 $SAI_TUB $sig true
done
for capability in $tap_capabilities; do
    sig=$(seth calldata $capability)
    seth send $SAI_MOM "setRoleCapability(uint8,address,bytes4,bool)" 1 $SAI_TAP $sig true
done
for capability in $top_capabilities; do
    sig=$(seth calldata $capability)
    seth send $SAI_MOM "setRoleCapability(uint8,address,bytes4,bool)" 1 $SAI_TOP $sig true
done
for capability in $lpc_capabilities; do
    sig=$(seth calldata $capability)
    seth send $SAI_MOM "setRoleCapability(uint8,address,bytes4,bool)" 1 $SAI_LPC $sig true
done
