#!/usr/bin/env bash
set -ex

export SOLC_FLAGS=${SOLC_FLAGS:-"--optimize"}
export ETH_GAS=${ETH_GAS:-"3900000"}

dapp build

export SETH_ASYNC=yes

SAItx=$(dapp create DSToken 'SAI' 'SAI' 18)
SINtx=$(dapp create DSToken 'SIN' 'SIN' 18)
test -z $SAI_GEM && GEMtx=$(dapp create DSToken 'ETH' 'ETH' 18)
test -z $SAI_PIP && PIPtx=$(dapp create DSValue)
test -z $SAI_MOM && MOMtx=$(dapp create DSRoles)
SKRtx=$(dapp create DSToken 'SKR' 'SKR' 18)
LPStx=$(dapp create DSToken 'LPS' 'LPS' 18)
POTtx=$(dapp create DSVault)
PITtx=$(dapp create DSVault)
TIPtx=$(dapp create Tip)

export SETH_ASYNC=no

SAI_SAI=$(seth receipt $SAItx contractAddress)
SAI_SIN=$(seth receipt $SINtx contractAddress)
SAI_DEV=$(dapp create DSDevil $SAI_SAI $SAI_SIN)
SAI_SKR=$(seth receipt $SKRtx contractAddress)
test -z $SAI_GEM && SAI_GEM=$(seth receipt $GEMtx contractAddress)
test -z $SAI_PIP && SAI_PIP=$(seth receipt $PIPtx contractAddress)
SAI_JAR=$(dapp create SaiJar $SAI_SKR $SAI_GEM $SAI_PIP)
test -z $SAI_MOM && SAI_MOM=$(seth receipt $MOMtx contractAddress) && seth send $SAI_MOM "setAuthority(address)" $SAI_MOM
SAI_POT=$(seth receipt $POTtx contractAddress)
SAI_PIT=$(seth receipt $PITtx contractAddress)
SAI_TIP=$(seth receipt $TIPtx contractAddress)

SAI_TUB=$(dapp create Tub $SAI_JAR $SAI_DEV $SAI_POT $SAI_PIT $SAI_TIP)
SAI_TAP=$(dapp create Tap $SAI_TUB $SAI_PIT)
SAI_TOP=$(dapp create Top $SAI_TUB $SAI_TAP)

SAI_LPS=$(seth receipt $LPStx contractAddress)
SAI_LPC=$(dapp create SaiLPC $SAI_SAI $SAI_GEM $SAI_PIP $SAI_LPS $SAI_TIP)

export SETH_ASYNC=yes
AUTH1tx=$(seth send $SAI_SKR "setAuthority(address)" $SAI_MOM)
AUTH2tx=$(seth send $SAI_POT "setAuthority(address)" $SAI_MOM)
AUTH3tx=$(seth send $SAI_TIP "setAuthority(address)" $SAI_MOM)
AUTH4tx=$(seth send $SAI_SAI "setAuthority(address)" $SAI_MOM)
AUTH5tx=$(seth send $SAI_SIN "setAuthority(address)" $SAI_MOM)
seth send $SAI_TUB "setAuthority(address)" $SAI_MOM
seth send $SAI_TAP "setAuthority(address)" $SAI_MOM
seth send $SAI_TOP "setAuthority(address)" $SAI_MOM
seth send $SAI_JAR "setAuthority(address)" $SAI_MOM
seth send $SAI_PIT "setAuthority(address)" $SAI_MOM
seth send $SAI_LPC "setAuthority(address)" $SAI_MOM
seth send $SAI_MOM "setRootUser(address,bool)" $ETH_FROM true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_TUB true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_DEV true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_TOP true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_TAP true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_JAR true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_POT true
seth send $SAI_MOM "setRootUser(address,bool)" $SAI_PIT true

seth send $SAI_LPS "setOwner(address)" $SAI_LPC
seth send $SAI_DEV "setOwner(address)" $SAI_TUB
export SETH_ASYNC=no

seth receipt $AUTH1tx
seth receipt $AUTH2tx
seth receipt $AUTH3tx
seth receipt $AUTH4tx
seth receipt $AUTH5tx

export SETH_ASYNC=yes
seth send $SAI_SKR "setOwner(address)" $SAI_TUB
seth send $SAI_POT "setOwner(address)" $SAI_TUB
seth send $SAI_TIP "setOwner(address)" $SAI_TUB
seth send $SAI_SAI "setOwner(address)" $SAI_DEV
seth send $SAI_SIN "setOwner(address)" $SAI_DEV

cat > load-env-$(seth chain) << EOF
#!/bin/bash

# sai deployment on $(seth chain) from $(git rev-parse HEAD)
# $(date)

export SAI_GEM=$SAI_GEM
export SAI_SAI=$SAI_SAI
export SAI_SIN=$SAI_SIN
export SAI_SKR=$SAI_SKR
export SAI_DEV=$SAI_DEV
export SAI_POT=$SAI_POT
export SAI_PIT=$SAI_PIT
export SAI_TIP=$SAI_TIP
export SAI_PIP=$SAI_PIP
export SAI_MOM=$SAI_MOM
export SAI_LPS=$SAI_LPS
export SAI_JAR=$SAI_JAR
export SAI_TUB=$SAI_TUB
export SAI_TAP=$SAI_TAP
export SAI_TOP=$SAI_TOP
export SAI_LPC=$SAI_LPC
EOF

echo SAI TUB DEPLOYED AT: $SAI_TUB
