#!/usr/bin/env bash
### dai-par -- get the accrued holder fee (ref per dai)
set -e
vox=$(seth call "${DAI_TUB?}" 'vox()')
vox_address="0x$(seth --abi-decode 'f()(address)' "$vox")"
ray=$(seth call "$vox_address" "par()")
dai ray -h "$ray"
