#!/usr/bin/env bash
### dai-way -- get the holder fee (interest rate)
set -e
vox=$(seth call "${DAI_TUB?}" 'vox()')
vox_address="0x$(seth --abi-decode 'f()(address)' "$vox")"
ray=$(seth call "$vox_address" "way()")
dai ray -h "$ray"
