#!/usr/bin/env bash
### dai-setTapGap -- update the spread on `boom` and `bust`
### Usage: dai tapGap <new-gap>
set -e
[ $# = 1 ] || dai tap tapGap --usage
wad=$(dai wad -h "$1")
echo >&2 "Setting gap to $wad..."
wad=$(dai wad "$1")
(set -x; seth send "${DAI_MOM?}" "setTapGap(uint256)" "$wad")
