#!/usr/bin/env bash
### dai-setCap -- update the debt ceiling
### Usage: dai setCap <new-cap>
set -e
[ $# = 1 ] || dai setCap --usage
wad=$(dai wad -h "$1")
echo >&2 "Setting cap to $wad..."
wad=$(dai wad "$1")
(set -x; seth send "${DAI_MOM?}" "setCap(uint256)" "$wad")
