#!/usr/bin/env bash
### sai-boom -- buy some amount of sai to process joy (surplus)
set -e
wad=$(sai wad -h "$1")
echo >&2 "Buying $wad SAI from the tub in order to process joy..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TUB?}" "boom(uint128)" "$wad")
