#!/usr/bin/env bash
### sai-cork -- update the debt ceiling
### Usage: sai cork <new-hat>
set -e
[ $# = 1 ] || sai cork --usage
wad=$(sai wad -h "$1")
echo >&2 "Setting hat to $wad..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TUB?}" "cork(uint256)" "$wad")
