#!/usr/bin/env bash
### sai-cage -- lock the system and initiate settlement
### Usage: sai cage [<final-price>]
###   if <final-price> is not specified, the last value from the feed will be used
set -e
if [ $# = 0 ]
then
  echo >&2 "Caging the tub, using the final price from the feed"
  (set -x; seth send "${SAI_TOP?}" "cage()")
elif [ $# = 1 ]
then
  wad=$(sai wad -h "$1")
  echo >&2 "Caging the tub, final price $wad"
  wad=$(sai wad "$1")
  (set -x; seth send "${SAI_TOP?}" "cage(uint256)" "$wad")
else
  sai cage --usage
fi
