#!/usr/bin/env bash
### sai-open -- create a new cup (collateralized debt position)
set -e
echo >&2 "Opening cup..."
export SETH_ASYNC=yes
tx=$(set -x; seth send "${SAI_TUB?}" "open()(bytes32)")
export SETH_ASYNC=no
echo >&2 -n "Waiting for transaction receipt..."
number=$(SETH_TICK=true seth receipt "$tx" blockNumber)
echo >&2
seth rpc eth_getLogs -- -n {} -s "${SAI_TUB?}" -i address \
                                 -s "$number"  -i fromBlock \
                                 -s "$number"  -i toBlock \
                                   -n [] -s "$(seth keccak "$(seth --from-ascii 'LogNewCup(address,bytes32)')")" -i append \
                                         -s "0x$(seth --to-uint256 "${ETH_FROM?}")" -i append \
                                   -i topics \
                           -i append \
  | echo "[$(paste -sd , -)]" `# --jsonrpc output is dejsoned :/ ` \
  | jshon -a -e data -u -p -e transactionHash -u \
  | grep -B 1 "$tx" \
  | head -1 \
  | seth --to-dec \
  | { read -r id; echo "Opened cup $id"; }
