#!/usr/bin/env bash
### sai-prod -- recalculate the accrued holder fee (par)
set -e
tip=$(seth call "${SAI_TUB?}" 'tip()')
tip_address="0x$(seth --abi-decode 'f()(address)' "$tip")"
(set -x; seth send "$tip_address" "prod()")
