#!/usr/bin/env bash
### sai-tap-jump -- update the spread on `boom` and `bust`
### Usage: sai tap jump <new-gap>
set -e
[ $# = 1 ] || sai jump --usage
wad=$(sai wad -h "$1")
echo >&2 "Setting gap to $wad..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TAP?}" "jump(uint128)" "$wad")
