#!/usr/bin/env bash
### sai-par -- get the accrued holder fee (ref per sai)
set -e
vox=$(seth call "${SAI_TUB?}" 'vox()')
vox_address="0x$(seth --abi-decode 'f()(address)' "$vox")"
ray=$(seth call "$vox_address" "par()")
sai ray -h "$ray"
