#!/usr/bin/env bash
### sai-cash -- cash in sai balance for gems after cage
set -e
sai=$(token balance "$(sai sai)" "${ETH_FROM?}")
echo >&2 "Cashing in $sai SAI..."
(set -x; seth send "${SAI_TOP?}" "cash()")
