#!/usr/bin/env bash
### sai-bite -- initiate liquidation of an undercollateral cup
set -e
echo >&2 "Attempting to bite cup id $((10#${SAI_CUP?}))..."
test "$(sai safe)" = true && seth --error bite "Cannot bite an overcollaterized cup!"
(set -x; seth send "${SAI_TUB?}" "bite(bytes32)" "$SAI_CUP")
