#!/usr/bin/env bash
### sai-cups -- list cups created by you
set -e
echo >&2 "Cups created by you..."
seth rpc eth_getLogs -- -n {} -s "${SAI_TUB?}" -i address \
                                 -s earliest    -i fromBlock \
                                   -n [] -s "$(seth keccak "$(seth --from-ascii 'LogNewCup(address,bytes32)')")" -i append \
                                         -s "0x$(seth --to-uint256 "${ETH_FROM?}")" -i append \
                                   -i topics \
                           -i append \
  | echo "[$(paste -sd , -)]" `# --jsonrpc output is dejsoned :/ ` \
  | jshon -a -e data \
  | seth --to-dec
