#!/usr/bin/env bash
### sai-cuff -- update the liquidation ratio
set -e
wad=$(sai wad -h "$1")
echo >&2 "Setting mat to $wad..."
wad=$(seth --to-uint256 $(sai wad "$1"))
(set -x; seth send "${SAI_TUB?}" "cuff(uint128)" "$wad")
