#!/usr/bin/env bash
### sai-free -- remove excess SKR collateral from a cup
### Usage: sai --cup=<id> free <amount-in-skr>
set -e
[ $# = 1 ] || sai free --usage
[ ! -z "$SAI_CUP" ] || sai free --usage
wad=$(sai wad -h "$1")
echo >&2 "Freeing $wad SKR from cup $((${SAI_CUP?}))..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TUB?}" "free(bytes32,uint256)" "$SAI_CUP" "$wad")
