#!/usr/bin/env bash
### sai-cage -- lock the system and initiate settlement
set -e
wad=$(sai wad -h "$1")
echo >&2 "Caging the tub, final price $wad"
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TUB?}" "kill(uint128)" "$wad")
