#!/usr/bin/env bash
### sai-jar-jump -- update the spread on `join` and `exit`
### Usage: sai jar jump <new-gap>
set -e
[ $# = 1 ] || sai jar jump --usage
wad=$(sai wad -h "$1")
echo >&2 "Setting gap to $wad..."
wad=$(sai wad "$1")
jar=$(seth call "${SAI_TUB?}" 'jar()')
jar_address="0x$(seth --abi-decode 'f()(address)' "$jar")"
(set -x; seth send "$jar_address" "jump(uint128)" "$wad")
