#!/usr/bin/env bash
### sai-cups -- list your cups
set -e
echo >&2 "Your cups ..."
seth rpc eth_getLogs -- -n {} -s ${SAI_TUB?} -i address \
                                 -s earliest    -i fromBlock \
                                   -n [] -s "$(seth keccak $(seth --from-ascii 'LogNewCup(address,bytes32)'))" -i append \
                                         -s "0x$(seth --to-uint256 $ETH_FROM)" -i append \
                                   -i topics \
                           -i append \
  | paste -sd , - `# --jsonrpc output is dejsoned :/ ` \
  | { read j;  echo "[$j]"; } \
  | jshon -a -e data \
  | seth --to-dec
