#!/usr/bin/env bash
### sai-coax -- update the holder fee (interest rate)
### Usage: sai coax <new-way>
set -e
[ $# = 1 ] || sai coax --usage
ray=$(sai ray -h "$1")
echo >&2 "Setting way to $ray..."
ray=$(sai ray "$1")
tip=$(seth call "${SAI_TUB?}" 'tip()')
tip_address="0x$(seth --abi-decode 'f()(address)' "$tip")"
(set -x; seth send $tip_address "coax(uint128)" "$ray")
