#!/usr/bin/env bash
### sai-tau -- get the time of last prod
set -e
tip=$(seth call "${SAI_TUB?}" 'tip()')
tip_address="0x$(seth --abi-decode 'f()(address)' "$tip")"
time=$(seth call "$tip_address" "tau()")
echo "$(seth --to-dec $time)"
