#!/usr/bin/env bash
### sai-bust -- sell some amount of sai to process woe (bad debt)
set -e
wad=$(sai wad -h "$1")
echo >&2 "Selling $wad SAI to the tub in order to process woe..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TUB?}" "bust(uint128)" "$wad")
