#!/usr/bin/env bash
### sai-pip -- get the gem price feed
set -e
jar=$(seth call "${SAI_TUB?}" 'jar()')
jar_address="0x$(seth --abi-decode 'f()(address)' "$jar")"
pip=$(seth call "$jar_address" "pip()")
echo "0x$(seth --abi-decode 'f()(address)' "$pip")"
