#!/usr/bin/env bash
### sai-chop -- update the liquidation penalty
set -e
wad=$(sai wad -h "$1")
echo >&2 "Setting axe to $wad..."
wad=$(seth --to-uint256 $(sai wad "$1"))
echo $wad
(set -x; seth send "${SAI_TUB?}" "chop(uint128)" "$wad")
