#!/usr/bin/env bash
### sai-tau -- get the time of last prod
set -e
vox=$(seth call "${SAI_TUB?}" 'vox()')
vox_address="0x$(seth --abi-decode 'f()(address)' "$vox")"
time=$(seth call "$vox_address" "tau()")
time_unix=$(seth --to-dec "$time")
echo "$time_unix"
