#!/usr/bin/env bash
### sai-setWay -- update the holder fee (interest rate)
### Usage: sai setWay <new-way>
set -e
[ $# = 1 ] || sai setWay --usage
ray=$(sai ray -h "$1")
echo >&2 "Setting way to $ray..."
ray=$(sai ray "$1")
(set -x; seth send "${SAI_MOM}" "setWay(uint256)" "$ray")
