#!/usr/bin/env bash
### sai-tab -- get the amount of debt in a cup
### Usage: sai --cup=<id> tab
set -e
[ ! -z "$SAI_CUP" ] || sai tab --usage
wad=$(seth call "${SAI_TUB?}" "tab(bytes32)" "${SAI_CUP?}")
sai wad -h "$wad"
