#!/usr/bin/env bash
### sai-chop -- update the liquidation penalty
set -e
ray=$(sai ray -h "$1")
echo >&2 "Setting axe to $ray..."
ray=$(sai ray "$1")
(set -x; seth send "${SAI_TUB?}" "chop(uint128)" "$ray")
