#!/usr/bin/env bash
### sai-cash -- cash in sai / skr balance for gems after kill
set -e
sai=$(token balance "$(sai sai)" "${ETH_FROM?}")
skr=$(token balance "$(sai skr)" "${ETH_FROM?}")
echo >&2 "Cashing in $sai SAI and $skr SKR..."
(set -x; seth send "${SAI_TUB?}" "cash()")
