#!/usr/bin/env bash
### sai-bust -- sell some amount of sai to process woe (bad debt)
### Usage: sai bust <amount-in-skr>
set -e
[ $# = 1 ] || sai bust --usage
wad=$(sai wad -h "$1")
echo >&2 "Selling $wad SKR-worth amount of SAI to the tub in order to process woe..."
wad=$(sai wad "$1")
(set -x; seth send "${SAI_TAP?}" "bust(uint256)" "$wad")
